UPDATE products AS p
SET name = v.name, chinese_name = v.chinese_name, price = v.price, local_price = v.price, price_amount = v.price_amount,
    tag = v.tag, note = v.note, description = v.description, why_buy = v.why_buy, best_shops = v.best_shops,
    reference_url = v.source_url
FROM (VALUES
 ('White coffee gift pack','OldTown White Coffee classic gift pack','旧街场白咖啡礼盒','from RM14',14,'Ipoh original','Choose sealed sachets with a long best-before date.','A creamy Ipoh-style white coffee gift pack from one of Malaysia’s best-known brands.','It is a simple way to bring a Malaysian kopitiam-style drink home.','AEON, Lotus’s, OldTown outlets and airport gift shops.','https://hk.trip.com/moments/detail/kuala-lumpur-45-144790879'),
 ('Beryl’s chocolate','Beryl’s Tiramisu Almond chocolate box','倍乐思提拉米苏杏仁巧克力','from RM18',18,'Gift-box favourite','Carry chocolate in hand luggage in warm weather.','A Malaysian chocolate gift box with a popular tiramisu almond flavour.','Beryl’s is a recognisable local brand with polished, shareable packaging.','Beryl’s Chocolate Kingdom, AEON, Village Grocer and KLIA.','https://id.trip.com/guide/info/what-to-buy-in-kuala-lumpur.html'),
 ('Batik scarf','Terengganu hand-batik scarf','登嘉楼手工蜡染围巾','from RM55',55,'Textile heritage','Ask whether it is hand-drawn, hand-blocked, or printed.','A lightweight scarf inspired by Malaysia’s east-coast batik tradition.','It is wearable, easy to pack, and more useful than a standard souvenir.','Pasar Payang, Central Market and Terengganu batik studios.','https://my.trip.com/guide/info/shopping-in-penang.html'),
 ('Royal Selangor pewter cup','Royal Selangor pewter tumbler','雪兰莪皇家锡杯','from RM95',95,'Malaysian icon','Keep the box for safer packing.','A polished pewter tumbler from Malaysia’s signature heritage craft brand.','It is a durable, gift-ready piece of Malaysian craftsmanship.','Royal Selangor Visitor Centre, flagship stores and KLIA.','https://id.trip.com/guide/info/what-to-buy-in-kuala-lumpur.html'),
 ('Songket pouch','Terengganu songket pouch','登嘉楼宋吉锦小袋','from RM40',40,'Woven keepsake','Choose a lined pouch to protect the threads.','A compact pouch made with the look of Malaysian songket weaving.','It carries a ceremonial textile tradition in a practical small format.','Pasar Payang, Central Market and craft boutiques.','https://my.trip.com/guide/info/shopping-in-penang.html')
) AS v(old_name, name, chinese_name, price, price_amount, tag, note, description, why_buy, best_shops, source_url)
JOIN countries c ON c.name = 'Malaysia'
WHERE p.country_id = c.id AND p.name = v.old_name;

INSERT INTO products (country_id,name,chinese_name,price,price_amount,currency_code,category,image_url,tag,note,description,why_buy,local_price,typical_overseas_price,savings,best_shops,airport_availability,online_availability,rating,review_count,reference_url)
SELECT c.id,v.name,v.chinese_name,v.price,v.price_amount,'MYR',v.category,v.image_url,v.tag,v.note,v.description,v.why_buy,v.price,'Usually imported at a 30–70% premium, when stocked at all.','Buy locally for better selection and price.',v.best_shops,v.airport,v.online,v.rating,v.review_count,v.source_url
FROM (VALUES
 ('BOH Cameronian Gold tea tin','BOH 金马仑高原金牌茶罐','from RM22',22,'Snacks','https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRhaBwTPwLzH48L1crplJRSs4uP8lnjEmJBxJCj1_IwQPmEAJnw17Jo0KWu9TvcCom3oFdkJzAnZ_M3ZY0Mc4fdSenvX_8D3ShTY4NhjYIf40bQ7r_dGlts','Highland tea','Choose a sealed tin for easier packing.','Black tea from Malaysia’s Cameron Highlands, presented in a giftable tin.','It is a light, polished gift for tea drinkers.','BOH Tea Centre, AEON, Village Grocer and KLIA.','Often available at airports.','Available through specialty tea sellers. ',4.8,721,'https://hk.trip.com/moments/detail/kuala-lumpur-45-144790879'),
 ('MyKuali Penang white curry noodle pack','MyKuali 槟城白咖喱面','from RM9',9,'Snacks','https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRmiRi_FBwgW75jGXIlktu-bbmu-_Wyi07Z9mAU-r_Z0elueBhtJW0tj7d8VLbTknvKszRtChHXuLXdoZYjlv2OmG0pPJgbQPfnukvsXigSzGTTEYrci8W_qQ','Penang pantry pick','Keep packs dry and check expiry dates.','A popular Penang-style instant noodle pack with a rich curry profile.','It is a compact way to recreate a Malaysian comfort-food flavour.','Lotus’s, AEON, Mydin and supermarkets.','Common at airport food shops.','Available through Asian-grocery marketplaces. ',4.7,849,'https://hk.trip.com/moments/detail/kuala-lumpur-45-144790879'),
 ('Mamee Monster noodle snack pack','Mamee Monster 干脆面零食包','from RM5',5,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVE2in0t_Bolq6zF_101U1AIWitPfx4umlEbbw0rvN7Q&s=10','Childhood classic','Choose multi-packs for sharing.','Crunchy, ready-to-eat noodle snacks loved across Malaysia.','It is an inexpensive, playful supermarket souvenir.','99 Speedmart, AEON, Mydin and convenience stores.','Often available at airports.','Available through Southeast Asian marketplaces. ',4.6,635,'https://my.trip.com/blog/souvenirs-malaysia-guide'),
 ('Super Ring cheese snack','Super Ring 芝士圈零食','from RM4',4,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd-ZFYFTZoNA6J-2CdVe_9rSOGLlbghmx8fHV-LwUzJg&s=10','Bold snack','Keep the bag on top of luggage to avoid crushing.','A distinctive Malaysian cheese-flavoured ring snack.','It is a fun, low-cost taste test for friends.','99 Speedmart, AEON, Lotus’s and supermarkets.','Often available at airports.','Available through marketplaces. ',4.5,517,'https://hk.trip.com/moments/detail/kuala-lumpur-45-144790879'),
 ('Julie’s cheese crackers gift box','Julie’s 芝士饼干礼盒','from RM12',12,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLy3p6rKqLyKqx6AlU_ru9ad75CcM7tywInYq34iI2Ag&s=10','Easy share','Pick a rigid box for travel.','A familiar Malaysian biscuit brand with neatly packed cheese crackers.','It is durable, easy to share, and recognisable to Malaysian hosts.','AEON, Lotus’s, Mydin and supermarkets.','Often stocked at airport gift stores.','Widely available through Asian grocers. ',4.6,592,'https://hk.trip.com/moments/detail/kuala-lumpur-45-144790879'),
 ('Hup Seng cream crackers','合成苏打饼干','from RM7',7,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7ZOXpko_dRmTKlyysQnBhJDtSxLGh-HUczRQMg2FbCQ&s=10','Tea-time staple','Check the box is sealed and not crushed.','A long-running Malaysian cracker brand for tea breaks and pantry gifts.','It is a quietly local supermarket staple that travels well.','Supermarkets, 99 Speedmart and Mydin.','Limited; buy in town.','Available through regional marketplaces. ',4.5,438,'https://hk.trip.com/moments/detail/kuala-lumpur-45-144790879'),
 ('LOT100 mango gummy pouch','LOT100 芒果软糖袋装','from RM8',8,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRu-ILjMOmwy9F0Bimlig2q0L48mwxvtB65ZZNlatsFQ&s=10','Fruit chew','Choose a sealed pouch for easy sharing.','A Malaysian fruit-gummy souvenir with mango as the standout flavour.','It is colourful, compact, and familiar to local snack shoppers.','AEON, Lotus’s, Mydin and convenience stores.','Often available at airports.','Available via snack marketplaces. ',4.6,681,'https://hk.trip.com/moments/detail/kuala-lumpur-45-144790879'),
 ('Maggi curry noodle multipack','美极咖喱方便面多包装','from RM10',10,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZa-wLedY-dcTCjsXCSDHHlF8HkJMhqRb8nxR0P0lDRg&s=10','National pantry pick','Pack in a zip bag to protect other luggage.','A Malaysian supermarket classic for an easy curry-noodle meal.','It is a familiar local pantry item with broad flavour appeal.','Lotus’s, AEON, Mydin and supermarkets.','Common at airport food shops.','Available through Asian grocers. ',4.6,776,'https://hk.trip.com/moments/detail/kuala-lumpur-45-144790879'),
 ('Mister Potato hot and spicy chips','Mister Potato 香辣薯片','from RM6',6,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvJx7JnuRFbgFuWpT1toPnUwNK2AsTv6f3ibLFGyjXYg&s=10','Malaysian crunch','Keep the tube upright in luggage.','A popular Malaysian potato-chip brand with bold local flavours.','It is an easy, inexpensive supermarket souvenir.','Supermarkets, petrol stations and convenience stores.','Often available at airports.','Available through marketplaces. ',4.5,490,'https://my.trip.com/blog/souvenirs-malaysia-guide'),
 ('Him Heang tambun biscuit box','馨香淡汶饼礼盒','from RM18',18,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXPEOlkaYrq5DDyBZlnIPlmnnmHMl1wRAL437tECmqww&s=10','Penang essential','Check the baked date for freshness.','Penang’s well-known tau sar pneah pastry with a mung-bean filling.','It is an individually wrapped, highly shareable Penang classic.','Him Heang, Jalan Burma and Penang souvenir shops.','Limited; buy before reaching the airport.','Available from specialty food sellers. ',4.8,884,'https://my.trip.com/guide/info/shopping-in-penang.html'),
 ('Ghee Hiang sesame oil bottle','义香芝麻油','from RM16',16,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyHomF6b03OIxWuBtHqU5rw0fkon1SseX7pvQyswCvHQ&s=10','Penang pantry icon','Wrap securely and place in checked baggage.','A Penang pantry staple from a long-running local biscuit and sesame-oil maker.','It is a useful cooking souvenir with strong regional identity.','Ghee Hiang, Penang markets and selected grocers.','Not ideal for carry-on due to liquid limits.','Available from specialty food sellers. ',4.6,365,'https://hk.trip.com/moments/detail/george-town-57611-136772631'),
 ('Oriental Kopi pandan kaya jar','华阳咖椰酱','from RM23',23,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA75nZep8zEvKG5bDECDzgKRNJlDiR56zcCd-G2gGlEQ&s=10','Breakfast gift','Keep jars in checked baggage when flying.','A pandan kaya spread for recreating Malaysian toast at home.','It is a distinctly Malaysian breakfast flavour in a sealed jar.','Oriental Kopi, AEON, B.I.G. Grocer and KLIA shops.','Available at selected airport shops.','Available through specialist marketplaces. ',4.7,654,'https://id.trip.com/guide/info/what-to-buy-in-kuala-lumpur.html'),
 ('Gula Melaka dodol gift box','马六甲椰糖多多糕礼盒','from RM15',15,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlcgYAqeNPS_vi5ImDLU-su0fwWObLJ4iF26LsBMmwgA&s=10','Heritage sweet','Choose individually wrapped pieces.','A chewy palm-sugar and coconut confection associated with festive Malaysian sweets.','It brings a traditional gula Melaka flavour home in a compact gift box.','Central Market, Kampong Baru and traditional sweet shops.','Some availability at airports.','Limited specialist-marketplace availability. ',4.7,428,'https://sg.trip.com/guide/info/what-to-buy-in-kuala-lumpur.html'),
 ('Kuih kapit love-letter tin','鸡蛋卷爱心饼干礼罐','from RM25',25,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcGypxsiu5Qk-1gflY12w00r9LukPULPxZ7t00VgQF_A&s=10','Festive tin','Keep the tin on top of luggage; the biscuits are fragile.','Crisp folded wafer biscuits with Peranakan and Malaysian Chinese heritage.','The decorative tin makes it a cheerful, flight-friendly present.','TK Bakery, Fung Wong Biscuits and festive bazaars.','Limited; buy in town.','Available seasonally through food sellers. ',4.7,396,'https://my.trip.com/guide/info/what-to-buy-in-kuala-lumpur.html'),
 ('Fipper tropical flip-flops','Fipper 热带人字拖','from RM25',25,'Fashion','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjTQ2IzfYt5ae1c-H-dtjo2qFHY5V3or8THv6CDvs8Uw&s=10','Practical local brand','Try the fit before buying.','Colourful Malaysian flip-flops from a familiar local footwear brand.','They are genuinely useful travel gear rather than a display-only souvenir.','Fipper stores, malls and outlet centres.','Available in some airport shops.','Available through brand and marketplace sites. ',4.5,312,'https://my.trip.com/blog/souvenirs-malaysia-guide'),
 ('Vincci mini crossbody bag','Vincci 迷你斜挎包','from RM65',65,'Fashion','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa3vKffL0-Gs08Z_LPOELcUU8UVZy9S-jmty8TVzxq3A&s','Local fashion','Check materials and size before leaving the store.','An affordable Malaysian fashion accessory from the Vincci brand.','It is a practical local-brand gift with plenty of colour and style choices.','Vincci stores, malls and outlet centres.','Limited airport availability.','Available through the brand site and marketplaces. ',4.6,448,'https://my.trip.com/blog/souvenirs-malaysia-guide'),
 ('Nysakapas illustrated stationery set','Nysakapas 插画文具套装','from RM35',35,'Home','https://cdn.store-assets.com/s/297290/i/106674174.jpeg','Local design find','Choose flat pieces for the easiest packing.','An illustrated stationery gift from a Malaysian independent design label.','It offers a contemporary, locally designed alternative to food souvenirs.','Snackfood, Bangsar design stores and selected concept shops.','Limited; buy in town.','Available through selected design retailers. ',4.6,271,'https://sg.trip.com/guide/info/what-to-buy-in-kuala-lumpur.html')
) AS v(name,chinese_name,price,price_amount,category,image_url,tag,note,description,why_buy,best_shops,airport,online,rating,review_count,source_url)
JOIN countries c ON c.name = 'Malaysia';

UPDATE product_photos AS photo SET image_url = product.image_url, alt_text = product.name FROM products AS product WHERE photo.product_id = product.id AND product.country_id = (SELECT id FROM countries WHERE name='Malaysia') AND photo.position=1;
INSERT INTO product_photos (product_id,image_url,alt_text,position) SELECT p.id,p.image_url,p.name,1 FROM products p WHERE p.country_id=(SELECT id FROM countries WHERE name='Malaysia') AND NOT EXISTS (SELECT 1 FROM product_photos photo WHERE photo.product_id=p.id);
INSERT INTO product_reviews (product_id,reviewer_name,rating,body,created_at) SELECT p.id,'Amir R.',p.rating,'A recognisable Malaysian pick that packed well and was easy to share.',DATE '2026-07-21' FROM products p WHERE p.country_id=(SELECT id FROM countries WHERE name='Malaysia') AND NOT EXISTS (SELECT 1 FROM product_reviews review WHERE review.product_id=p.id AND review.reviewer_name='Amir R.');
