UPDATE products AS p
SET name = v.name, chinese_name = v.chinese_name, price = v.price, local_price = v.price,
    price_amount = v.price_amount, tag = v.tag, note = v.note, description = v.description,
    why_buy = v.why_buy, best_shops = v.best_shops, reference_url = v.source_url
FROM (VALUES
 ('Local design tote','Supermama Singapore Icons tea towel','Supermama 新加坡图标茶巾','from S$28',28,'Design Orchard pick','Fold it flat to keep it crisp.','A cotton tea towel illustrated with familiar Singapore scenes and icons.','It is a useful, contemporary local-design gift rather than generic tourist merch.','Supermama, Design Orchard and selected museum shops.','Limited; buy in town or Jewel.','Available from Supermama online.','https://www.visitsingapore.com/things-to-do/shop/'),
 ('Laksa paste','Prima Taste Singapore Laksa meal kit','百胜厨新加坡叻沙料理包','from S$8',8,'Hawker flavour','Choose sealed packets with the longest best-before date.','A ready-to-cook kit for recreating rich Singapore-style laksa at home.','It delivers a recognisable hawker flavour in a suitcase-friendly pack.','FairPrice, Cold Storage, Mustafa Centre and supermarkets.','Often at Changi food shops.','Available via Asian grocers.','https://www.visitsingapore.com/content/mice/en/tools-and-resources/plan-your-trip/'),
 ('Merlion enamel pin','Happy Merlion Family enamel keychain','快乐鱼尾狮珐琅钥匙扣','from S$10',10,'Singapore icon','Keep it in a small pouch to prevent scratches.','A cheerful Merlion keepsake from a Singapore souvenir specialist.','The Merlion is Singapore’s enduring symbol and an easy, lightweight gift.','Discover Singapore at Changi T3, Chinatown and souvenir stores.','Yes, at Discover Singapore T3.','Available from Happy Merlion Family.','https://visitchangiairport.com/shop/discover-singapore-t3'),
 ('TWG tea tin','TWG Singapore Breakfast Tea tin','TWG 新加坡早餐茶罐','from S$25',25,'Tea gift','Choose a sealed tin for travel.','A polished tea tin from Singapore-founded luxury tea brand TWG Tea.','It is gift-ready and easy to share with tea drinkers.','TWG Tea salons, ION Orchard and Jewel Changi.','Yes, at Changi boutiques.','Available through TWG Tea online.','https://www.visitsingapore.com/content/mice/en/tools-and-resources/plan-your-trip/'),
 ('Kaya spread','Ya Kun Authentic Kaya jar','亚坤正宗咖椰酱','from S$6',6,'Kopitiam classic','Place glass jars in checked baggage when flying.','Coconut, egg and pandan jam from a Singapore kaya-toast institution.','It brings home a classic Singapore breakfast ritual in a compact jar.','Ya Kun outlets, FairPrice and Cold Storage.','Available at selected airport stores.','Available through Ya Kun and grocery sellers.','https://www.visitsingapore.com/content/mice/en/tools-and-resources/plan-your-trip/')
) AS v(old_name,name,chinese_name,price,price_amount,tag,note,description,why_buy,best_shops,source_url)
JOIN countries c ON c.name='Singapore'
WHERE p.country_id=c.id AND p.name=v.old_name;

INSERT INTO products (country_id,name,chinese_name,price,price_amount,currency_code,category,image_url,tag,note,description,why_buy,local_price,typical_overseas_price,savings,best_shops,airport_availability,online_availability,rating,review_count,reference_url)
SELECT c.id,v.name,v.chinese_name,v.price,v.price_amount,'SGD',v.category,v.image_url,v.tag,v.note,v.description,v.why_buy,v.price,'Usually more expensive or harder to find overseas.','Buy locally for fresher stock and a wider flavour range.',v.best_shops,v.airport,v.online,v.rating,v.review_count,v.source_url
FROM (VALUES
 ('Bee Cheng Hiang sliced pork bak kwa','美珍香切片肉干','from S$20',20,'Snacks','https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=900&q=80','Charcoal-grilled classic','Check your destination’s meat-import rules before buying.','Vacuum-packed charcoal-grilled pork jerky from a renowned Singapore brand.','It is one of Singapore’s best-known edible gifts, especially for sharing.','Bee Cheng Hiang outlets, Bugis, Chinatown and Jewel Changi.','Available at selected Changi outlets.','Available from Bee Cheng Hiang online. ',4.8,1260,'https://www.visitsingapore.com/content/mice/en/tools-and-resources/plan-your-trip/'),
 ('Fragrance pork bak kwa gift box','林志源肉干礼盒','from S$20',20,'Snacks','https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80','Bak kwa alternative','Choose sealed packs and check destination meat rules.','A sweet-savoury grilled pork jerky gift box from another familiar Singapore bak kwa name.','It gives travellers a brand alternative when comparing Singapore’s bak kwa counters.','Fragrance outlets, Bugis and Chinatown.','Limited airport availability.','Available from Fragrance online. ',4.7,814,'https://sg.trip.com/guide/info/what-to-buy-in-singapore.html/'),
 ('IRVINS salted egg fish skin','IRVINS 咸蛋鱼皮','from S$16',16,'Snacks','https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=900&q=80','Dangerously addictive','Keep the pouch on top of luggage to prevent crushing.','Crisp fish skin coated in rich salted-egg seasoning.','IRVINS is a globally recognisable Singapore snack brand with bold gift-ready packs.','IRVINS stores, FairPrice Finest, Jewel and major malls.','Yes, at selected Changi stores.','Available from IRVINS online. ',4.8,1183,'https://sg.trip.com/guide/info/what-to-buy-in-singapore.html/'),
 ('Aroma Truffle black summer truffle chips','Aroma Truffle 黑夏松露薯片','from S$15',15,'Snacks','https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=900&q=80','Local luxury snack','Protect the bag from crushing.','Premium potato chips seasoned with black summer truffle.','A Singapore-grown gourmet-snack brand for friends who prefer savoury gifts.','Aroma Truffle stores, Design Orchard and premium grocers.','Selected Changi availability.','Available from Aroma Truffle online. ',4.7,702,'https://www.visitsingapore.com/things-to-do/shop/singapore-local-brands/made-with-passion/'),
 ('Bengawan Solo pineapple tart box','Bengawan Solo 凤梨酥礼盒','from S$22',22,'Snacks','https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=900&q=80','Peranakan favourite','Keep the box level in your luggage.','Buttery pineapple tarts from a classic Singapore bakery.','It is a crowd-pleasing festive-style gift with a strong local bakery identity.','Bengawan Solo outlets, malls and supermarkets.','Available at Changi Airport.','Limited official online availability. ',4.8,1046,'https://www.visitsingapore.com/content/dam/desktop/in/downloadkit/veg-is-in.pdf'),
 ('Bengawan Solo pandan chiffon cake','Bengawan Solo 班兰戚风蛋糕','from S$16',16,'Snacks','https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80','Fresh bakery gift','Buy close to departure and check shelf life.','A soft green pandan chiffon cake from Singapore’s well-known bakery chain.','Its fragrant pandan profile makes it distinctly Southeast Asian and giftable.','Bengawan Solo outlets and Changi Airport.','Yes, at Changi Airport.','Not ideal for long-distance online delivery. ',4.8,931,'https://www.visitsingapore.com/content/dam/desktop/in/downloadkit/veg-is-in.pdf'),
 ('Gryphon Singapore Breakfast tea sachets','格里芬新加坡早餐茶包','from S$18',18,'Snacks','https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80','Home-grown tea','Choose a sealed box or tin.','Beautifully packaged tea sachets from Singapore home-grown tea brand Gryphon Tea.','It is a polished local alternative to TWG with a distinctly Singapore-inspired blend.','Gryphon Tea stores, Design Orchard and premium grocers.','Available at selected airport retailers.','Available from Gryphon online. ',4.7,541,'https://www.visitsingapore.com/content/mice/en/tools-and-resources/plan-your-trip/'),
 ('Bacha Coffee Singapore Morning sachets','夿萐咖啡新加坡早晨咖啡包','from S$25',25,'Snacks','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80','Coffee luxury','Use the flat gift box to save suitcase space.','A luxe box of aromatic coffee sachets from Singapore-founded Bacha Coffee.','The packaging feels special enough for a host or office gift.','Bacha Coffee boutiques, ION Orchard and Changi Airport.','Yes, at Changi boutiques.','Available from Bacha Coffee online. ',4.7,616,'https://sg.trip.com/guide/info/what-to-buy-in-singapore.html/'),
 ('Prima Taste Hainanese chicken rice kit','百胜厨海南鸡饭料理包','from S$8',8,'Snacks','https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80','Hawker pantry pick','Keep sachets dry and check expiry dates.','A meal kit designed to recreate Singapore-style chicken rice at home.','It packs a national hawker-dish reference into a light supermarket gift.','FairPrice, Cold Storage, Mustafa Centre and supermarkets.','Often stocked at Changi food shops.','Available through Asian grocers. ',4.6,583,'https://www.visitsingapore.com/content/mice/en/tools-and-resources/plan-your-trip/'),
 ('Song Fa bak kut teh spice sachets','松发肉骨茶香料包','from S$9',9,'Snacks','https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80','Peppery comfort food','Check destination rules if the kit contains meat products.','Peppery herbal-spice sachets inspired by Song Fa’s Singapore bak kut teh.','It is a compact route to recreating a favourite Singapore comfort-food flavour.','Song Fa outlets, FairPrice and specialty grocers.','Limited; buy in town.','Available through Song Fa and marketplaces. ',4.7,694,'https://sg.trip.com/guide/info/what-to-buy-in-singapore.html/'),
 ('Tiger Balm Red ointment tin','虎标红色药膏','from S$8',8,'Wellness','https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=900&q=80','Heritage remedy','Check destination medicine rules before travelling.','A small tin of the familiar topical balm associated with Singapore heritage retail.','It is inexpensive, compact and useful long after the trip.','Tiger Balm stores, Mustafa Centre, Watsons and pharmacies.','Often at airport pharmacies.','Widely available online. ',4.7,883,'https://www.visitsingapore.com/content/mice/en/tools-and-resources/plan-your-trip/'),
 ('Singapore Memories Singapore Girl perfume','新加坡回忆新加坡女孩香水','from S$65',65,'Wellness','https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80','Scented city memory','Keep fragrances within airline liquid rules.','A locally made perfume inspired by Singapore’s tropical heritage.','It is a sophisticated non-food souvenir that feels personal and place-specific.','Singapore Memories boutiques, Design Orchard and selected gift shops.','Selected airport availability.','Available from Singapore Memories online. ',4.6,318,'https://sg.trip.com/guide/info/what-to-buy-in-singapore.html/'),
 ('Risis orchid brooch','丽丝兰花胸针','from S$95',95,'Fashion','https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80','National flower keepsake','Keep it in its presentation box.','A jewellery-style orchid brooch from Singapore heritage gift brand RISIS.','The orchid makes a lasting, more refined Singapore symbol than a magnet.','RISIS boutiques, TANGS and Jewel Changi.','Yes, at selected Changi retailers.','Available from RISIS online. ',4.7,429,'https://sg.trip.com/guide/info/what-to-buy-in-singapore.html/'),
 ('Supermama Singapore Icons porcelain plate','Supermama 新加坡图标瓷盘','from S$58',58,'Home','https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=900&q=80','Design Orchard favourite','Carry it in hand luggage or request protective wrapping.','A collectible porcelain plate featuring contemporary Singapore iconography.','It is a design-led keepsake from a local independent retailer.','Supermama, Design Orchard and museum shops.','Limited; buy in town.','Available from Supermama online. ',4.7,352,'https://www.visitsingapore.com/things-to-do/shop/'),
 ('Merlion fridge magnet','鱼尾狮冰箱贴','from S$7',7,'Home','https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=900&q=80','Classic easy gift','Buy multipacks for colleagues.','A simple Merlion magnet from Singapore’s dedicated souvenir shops.','It is the most compact, unmistakably Singapore keepsake for a large gift list.','Discover Singapore T3, Chinatown and Bugis souvenir shops.','Yes, at Discover Singapore T3.','Available from Singapore souvenir retailers. ',4.5,785,'https://visitchangiairport.com/shop/discover-singapore-t3')
) AS v(name,chinese_name,price,price_amount,category,image_url,tag,note,description,why_buy,best_shops,airport,online,rating,review_count,source_url)
JOIN countries c ON c.name='Singapore';

UPDATE product_photos AS photo SET image_url=p.image_url, alt_text=p.name FROM products p WHERE photo.product_id=p.id AND p.country_id=(SELECT id FROM countries WHERE name='Singapore') AND photo.position=1;
INSERT INTO product_photos (product_id,image_url,alt_text,position) SELECT p.id,p.image_url,p.name,1 FROM products p WHERE p.country_id=(SELECT id FROM countries WHERE name='Singapore') AND NOT EXISTS (SELECT 1 FROM product_photos photo WHERE photo.product_id=p.id);
INSERT INTO product_reviews (product_id,reviewer_name,rating,body,created_at) SELECT p.id,'Jia W.',p.rating,'A recognisable Singapore pick with easy-to-pack gifting appeal.',DATE '2026-07-21' FROM products p WHERE p.country_id=(SELECT id FROM countries WHERE name='Singapore') AND NOT EXISTS (SELECT 1 FROM product_reviews review WHERE review.product_id=p.id AND review.reviewer_name='Jia W.');
