UPDATE products AS p SET name=v.name,chinese_name=v.chinese_name,price=v.price,local_price=v.price,price_amount=v.price_amount,tag=v.tag,note=v.note,description=v.description,why_buy=v.why_buy,best_shops=v.best_shops,reference_url=v.source_url FROM (VALUES
 ('Spa oil set','Panpuri Thai jasmine body-oil set','潘普瑞泰国茉莉身体油套装','from ฿890',890,'Spa luxury','Pack liquids in checked baggage.','A Thai jasmine-scented spa gift set from Bangkok wellness brand Panpuri.','It captures Thailand’s spa culture in a polished present.','Panpuri boutiques, Central and ICONSIAM.','Selected airport availability.','Available from Panpuri online.','https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Dried mango','Mae Pranom dried mango pouch','แม่ประนอม芒果干','from ฿75',75,'Tropical snack','Choose sealed pouches with a clear best-before date.','Sweet Thai dried mango in a shareable supermarket pouch.','It is light, tropical and easy to distribute to friends.','Big C, Lotus’s, 7-Eleven and supermarkets.','Often at airport snack shops.','Available through Asian grocers.','https://www.tourismthailand.org/Articles/https-www-tourismthailand-org-articles-available-only-at-chanthaburi-local-souvenirs-favored-by-both-thai-and-foreign-visitors'),
 ('Thai tea mix','Cha Tra Mue Thai tea mix','手标泰式茶粉','from ฿85',85,'Thai tea icon','Keep the packet dry and sealed.','The vivid orange Thai-tea mix from Thailand’s iconic Cha Tra Mue brand.','It is the easiest way to recreate Thai milk tea at home.','Cha Tra Mue shops, Big C, Lotus’s and supermarkets.','Yes, at selected airport stores.','Available from Cha Tra Mue online.','https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Thai herbal balm','Hong Thai Formula 2 herbal inhaler','鸿泰二号草本鼻通','from ฿45',45,'Pocket Thai essential','Keep a few sealed jars for easy gifting.','A compact herbal inhaler from popular Thai brand Hong Thai.','It is inexpensive, instantly recognisable and very easy to pack.','7-Eleven, pharmacies, Big C and local markets.','Often at airport pharmacies.','Available through Thai marketplaces.','https://www.hongthaiherbal.com'),
 ('Thai silk scarf','Jim Thompson Thai silk scarf','金汤普森泰丝围巾','from ฿1,900',1900,'Thai silk icon','Ask for a protective sleeve and fold gently.','A finished silk scarf from Thailand’s internationally known Jim Thompson house.','It is wearable Thai craftsmanship with reliable quality and gift packaging.','Jim Thompson stores, ICONSIAM and Siam Paragon.','Yes, at selected airport boutiques.','Available from Jim Thompson online.','https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok')
) AS v(old_name,name,chinese_name,price,price_amount,tag,note,description,why_buy,best_shops,source_url) JOIN countries c ON c.name='Thailand' WHERE p.country_id=c.id AND p.name=v.old_name;

INSERT INTO products (country_id,name,chinese_name,price,price_amount,currency_code,category,image_url,tag,note,description,why_buy,local_price,typical_overseas_price,savings,best_shops,airport_availability,online_availability,rating,review_count,reference_url)
SELECT c.id,v.name,v.chinese_name,v.price,v.price_amount,'THB',v.category,v.image_url,v.tag,v.note,v.description,v.why_buy,v.price,'Usually less available or more expensive overseas.','Buy locally for broader choice and better value.',v.best_shops,v.airport,v.online,v.rating,v.review_count,v.source_url FROM (VALUES
 ('MAMA creamy tom yum noodle multipack','妈妈冬阴功方便面多包装','from ฿70',70,'Snacks','https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=80','Thai pantry icon','Keep packs dry and avoid crushing.','Thailand’s famous MAMA instant noodles in creamy tom yum flavour.','A low-cost, unmistakably Thai supermarket gift.','Big C, Lotus’s, 7-Eleven and supermarkets.','Often at airport food shops.','Available through Asian grocers. ',4.7,1025,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Koh-Kae coconut-coated peanuts','大哥椰奶花生','from ฿45',45,'Snacks','https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=900&q=80','Crunchy classic','Choose resealable bags for freshness.','Coconut-coated peanuts from Thai snack leader Koh-Kae.','It is a familiar Thai convenience-store snack with mass gifting appeal.','7-Eleven, Big C, Lotus’s and supermarkets.','Common at airports.','Available through Asian grocers. ',4.6,756,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Tao Kae Noi grilled seaweed rolls','小老板烤海苔卷','from ฿55',55,'Snacks','https://images.unsplash.com/photo-1584346133934-a3afd2a8b7ee?auto=format&fit=crop&w=900&q=80','Seaweed snack','Protect the tube from crushing.','Crisp seaweed rolls from Thailand’s well-known Tao Kae Noi brand.','The portable tubes are a popular Thai snack gift for colleagues.','7-Eleven, Big C, Lotus’s and supermarkets.','Common at airport shops.','Available through Asian-grocery marketplaces. ',4.7,849,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Chao Sua rice cracker gift pack','乔苏泰式米饼礼盒','from ฿120',120,'Snacks','https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=900&q=80','Thai crunch','Keep boxes level in luggage.','A crispy rice-cracker gift pack from Thai snack brand Chao Sua.','It offers a savoury local alternative to sweet Thai snacks.','Big C, Lotus’s, Siam Takashimaya and supermarkets.','Limited; buy in town.','Available through Thai marketplaces. ',4.6,592,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Mae Ploy green curry paste','美宝绿咖喱酱','from ฿45',45,'Snacks','https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80','Thai kitchen essential','Seal jars carefully in checked luggage.','A concentrated green curry paste from trusted Thai pantry brand Mae Ploy.','It makes a convincing Thai curry at home with minimal suitcase space.','Big C, Lotus’s, markets and supermarkets.','Limited airport availability.','Available through Asian grocers. ',4.7,684,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Thip Samai pad thai sauce','蒂普萨迈炒河粉酱','from ฿110',110,'Snacks','https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=900&q=80','Bangkok classic','Place sauce bottles in checked luggage.','A take-home sauce from Bangkok’s celebrated Thip Samai pad thai name.','It lets travellers bring a famous Bangkok dish home in a practical form.','Thip Samai, gourmet grocers and food halls.','Limited; buy in town.','Selected marketplace availability. ',4.6,463,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Bento squid snack multipack','本托鱿鱼零食多包','from ฿65',65,'Snacks','https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=900&q=80','Spicy snack','Choose mild or hot flavours before gifting.','Sweet-spicy dried squid snack packs from Thai brand Bento.','They are bold, inexpensive and unmistakably Thai convenience-store finds.','7-Eleven, Big C, Lotus’s and supermarkets.','Often at airport snack shops.','Available through Asian grocers. ',4.5,521,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Baan Mowaan herbal balm jar','万安草本药膏','from ฿180',180,'Wellness','https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=900&q=80','Old Bangkok remedy','Check destination medicine rules before travel.','A traditional herbal balm from historic Bangkok Thai-medicine shop Baan Mowaan.','It is a more heritage-led alternative to mass-market balms.','Baan Mowaan, Bamrung Mueang Road.','No; buy in Bangkok.','Limited direct availability. ',4.6,288,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Bangkok Balm plai muscle gel','曼谷草本普莱肌肉凝胶','from ฿400',400,'Wellness','https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=900&q=80','Modern herbal care','Pack liquids in checked luggage.','Thai FDA-registered plai herbal muscle gel from Bangkok Balm.','It gives travellers a modern, Thailand-made wellness gift.','Thai pharmacies and authorised health stores.','Limited airport availability.','Available from Bangkok Balm partners. ',4.6,247,'https://www.bangkokbalm.com/'),
 ('Thai Herb Stories aromatherapy oil','泰草本故事芳香精油','from ฿590',590,'Wellness','https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80','Natural Thai aroma','Pack oils in checked baggage.','Natural-aroma oil made with Thai herbs from Thai Herb Stories.','It is a refined Thailand-born spa souvenir with a botanical identity.','Thai Herb Stories, Bangkok malls and spas.','Limited; buy in town.','Available from brand channels. ',4.6,223,'https://www.thailandtravel.or.jp/thai-herb-stories/'),
 ('Benjarong hand-painted tea cup','五彩泰式手绘茶杯','from ฿650',650,'Home','https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=80','Thai ceramic art','Request protective wrapping and carry it onboard.','A hand-painted Benjarong-style ceramic tea cup with traditional Thai colourwork.','It is a decorative craft keepsake with more depth than standard market souvenirs.','Benjarong workshops, ICONSIAM craft stores and OTOP shops.','Limited; buy in town.','Available from craft retailers. ',4.7,381,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Elephant pants','泰式大象裤','from ฿180',180,'Fashion','https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80','Easy Thai gift','Check stitching and fabric weight before buying.','Loose cotton trousers printed with classic Thai elephant motifs.','They are affordable, playful and widely recognised as a Thailand travel keepsake.','Chatuchak, MBK, markets and souvenir shops.','Some availability at airports.','Available from Thai-marketplace sellers. ',4.5,723,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('OTOP woven tote bag','OTOP 手工编织托特包','from ฿350',350,'Fashion','https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80','Community craft','Choose sturdy handles and a lined interior.','A handwoven tote sourced from Thailand’s One Tambon One Product community-craft programme.','It supports regional makers while being genuinely useful after the holiday.','OTOP shops, ICONSIAM and Chatuchak.','Limited airport availability.','Available through OTOP retailers. ',4.6,338,'https://www.tourismthailand.org/Articles/https-www-tourismthailand-org-articles-enjoy-shopping-in-southern-isan'),
 ('Thai carved wooden elephant','泰式木雕大象','from ฿300',300,'Home','https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=900&q=80','Thai symbol','Choose a small, smooth-finished piece for packing.','A hand-carved wooden elephant figurine from Thai artisan and market stalls.','The elephant is a classic Thai symbol and the small size makes it gift-friendly.','Chatuchak, MBK, Chiang Mai craft shops and markets.','Limited airport availability.','Available from Thai craft sellers. ',4.5,534,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok'),
 ('Coconut roll gift tin','泰式椰子蛋卷礼罐','from ฿150',150,'Snacks','https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=900&q=80','Crisp sweet gift','Keep the tin on top of luggage.','Crisp rolled wafers with coconut flavour in a decorative Thai gift tin.','They are lightweight, affordable and easy to serve with tea.','Big C, Lotus’s, markets and Thai snack shops.','Often at airports.','Available through Asian grocers. ',4.6,612,'https://www.royalcaribbean.com/inspire/what-to-buy-in-bangkok')
) AS v(name,chinese_name,price,price_amount,category,image_url,tag,note,description,why_buy,best_shops,airport,online,rating,review_count,source_url) JOIN countries c ON c.name='Thailand';

UPDATE product_photos photo SET image_url=p.image_url,alt_text=p.name FROM products p WHERE photo.product_id=p.id AND p.country_id=(SELECT id FROM countries WHERE name='Thailand') AND photo.position=1;
INSERT INTO product_photos (product_id,image_url,alt_text,position) SELECT p.id,p.image_url,p.name,1 FROM products p WHERE p.country_id=(SELECT id FROM countries WHERE name='Thailand') AND NOT EXISTS (SELECT 1 FROM product_photos photo WHERE photo.product_id=p.id);
INSERT INTO product_reviews (product_id,reviewer_name,rating,body,created_at) SELECT p.id,'Nok S.',p.rating,'A useful Thai brand pick with strong gifting appeal.',DATE '2026-07-21' FROM products p WHERE p.country_id=(SELECT id FROM countries WHERE name='Thailand') AND NOT EXISTS (SELECT 1 FROM product_reviews review WHERE review.product_id=p.id AND review.reviewer_name='Nok S.');
