INSERT INTO countries (slug,name,chinese_name,flag,city,buy,chinese_buy,tip,chinese_tip,shopping_location,reference_url)
VALUES ('japan','Japan','日本','🇯🇵','Tokyo','beautifully wrapped regional sweets, craft and stationery','精美包装的地区甜点、工艺品与文具','Japan excels at omiyage: look for sealed, shareable boxes and keep fragile crafts in hand luggage.','日本的伴手礼文化非常成熟：选择密封、方便分享的礼盒，易碎工艺品请随身携带。','Tokyo Station, department-store basements, Don Quijote, Hands and major airports.','https://www.japan.travel/en/guide/shopping-in-japan/');

INSERT INTO products (country_id,name,chinese_name,price,price_amount,currency_code,category,image_url,tag,note,description,why_buy,local_price,typical_overseas_price,savings,best_shops,airport_availability,online_availability,rating,review_count,reference_url)
SELECT c.id,v.name,v.chinese_name,v.price,v.price_amount,'JPY',v.category,v.image_url,v.tag,v.note,v.description,v.why_buy,v.price,'Often marked up overseas or unavailable outside Japan.','Buy in Japan for regional editions, freshness and wider selection.',v.best_shops,v.airport,v.online,v.rating,v.review_count,v.source_url FROM (VALUES
 ('Tokyo Banana original gift box','东京香蕉蛋糕礼盒','from ¥1,300',1300,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLl-S42rbWh0d-eKHmt6RMfUakESG9ZrJVRBynTrhrMA&s=10','Tokyo classic','Buy close to departure and protect the box.','Soft banana-shaped sponge cakes with banana custard filling.','It is one of Tokyo’s most recognisable individually wrapped omiyage gifts.','Tokyo Station, Tokyo Solamachi and major department stores.','Yes, at Haneda and Narita.','Available from official Japanese retailers. ',4.8,1432,'https://www.kkday.com/en/blog/57545/top-10-must-buy-souvenirs-in-tokyo'),
 ('Tokyo Milk Cheese Factory Salt & Camembert cookies','东京牛奶芝士工坊咸卡门贝尔饼干','from ¥1,350',1350,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkfRlmkTSmH2r_Nu8eG8bAGSsCD2lzhnu17SUJ0Z7E8g&s=10','Cheese-cookie hit','Choose the assorted box for sharing.','Crisp cookies pairing milk, salt and Camembert cheese.','The brand is a modern Tokyo favourite with elegant gift boxes.','Tokyo Station, Haneda Airport and department stores.','Yes, at Haneda and Narita.','Available through official Japanese shops. ',4.8,1068,'https://www.kkday.com/en/blog/57545/top-10-must-buy-souvenirs-in-tokyo'),
 ('Shiroi Koibito white-chocolate cookies','白色恋人白巧克力饼干','from ¥1,050',1050,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQojCaXRzk5o5_ZDm2ETbsE-Yi9C8bHRIrGj-ohRkA8cA&s=10','Hokkaido icon','Keep the box flat to avoid breakage.','Two langue de chat cookies sandwiching a square of white chocolate.','It is Hokkaido’s classic boxed souvenir and a reliable office gift.','Hokkaido shops, department stores and airports.','Yes, at major airports.','Available from Ishiya online. ',4.8,1195,'https://www.japan.travel/en/guide/last-minute-souvenirs/'),
 ('Royce Nama Chocolate au lait','罗伊斯生巧克力原味','from ¥1,080',1080,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYg7Q0hIH8aFzIktbbXkul_W9L-3kGg7Zh1G3nCUD2WQ&s','Hokkaido chocolate','Keep chilled and check your transfer time.','Silky fresh chocolate from Hokkaido confectioner Royce.','It is a luxurious Japan gift that feels far more special than standard chocolate.','Royce stores, department stores and Hokkaido outlets.','Yes, with chilled handling.','Available from Royce online. ',4.9,1127,'https://www.japan.travel/en/guide/last-minute-souvenirs/'),
 ('N.Y. Caramel Sand cookie box','纽约焦糖夹心饼干礼盒','from ¥1,350',1350,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO-fCaiENhy59ypWshGc7KrbqhSdnkE9lUNb8w51IbKA&s=10','Tokyo Station favourite','Buy early; popular flavours sell out.','Caramel and chocolate sandwiched between crisp cookies.','A highly sought-after Tokyo Station gift with a polished presentation.','Tokyo Station Gransta and selected department stores.','Limited airport availability.','Limited official online sales. ',4.8,987,'https://www.japan.travel/en/guide/last-minute-souvenirs/'),
 ('KitKat Japan regional flavour box','日本地区限定奇巧巧克力礼盒','from ¥900',900,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStx4RvQbtUzxJIybR6tXaGKk5KbtRVGyw8eoeZeZEzjg&s=10','Regional edition','Look for place-specific flavours.','Japan-only KitKat flavours such as matcha, sake and regional fruit.','They are inexpensive, colourful and easy to split into individual gifts.','Don Quijote, supermarkets, drugstores and station shops.','Yes, at major airports.','Available through Japanese snack retailers. ',4.7,1369,'https://www.japan.travel/en/guide/last-minute-souvenirs/'),
 ('Uji matcha gift tin','宇治抹茶礼罐','from ¥1,500',1500,'Snacks','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWXd86LMpw3rKefdk6uo_2W6Gwdlf3qF3uZ4POh362Hw&s=10','Kyoto tea ritual','Choose a sealed tin and keep it dry.','Fine green tea powder from Kyoto’s Uji tea tradition.','It is a refined, lightweight gift for tea and baking enthusiasts.','Ippodo, Nakamura Tokichi, Kyoto tea shops and department stores.','Available at selected airports.','Available through specialist tea sellers. ',4.8,744,'https://www.japan.travel/en/story/shopping-in-kyoto/'),
 ('Nishijin-ori silk pouch','西阵织丝绸小袋','from ¥2,200',2200,'Fashion','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjbvNtujUMz8UEPHggnvyQgS994_p2KBYbfb-YOh-JIQ&s=10','Kyoto textile','Choose a lined pouch and keep it dry.','A small pouch made with Kyoto’s richly patterned Nishijin woven textile.','It brings home heritage fabric in a practical, packable form.','Kyoto craft shops, Nishijin district and museum stores.','Limited; buy in Kyoto.','Available from selected craft retailers. ',4.7,428,'https://www.japan.travel/en/local-specialities/local-crafts/'),
 ('Furoshiki wrapping cloth','风吕敷日式包袱布','from ¥1,200',1200,'Fashion','https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=900&q=80','Reusable Japanese design','Choose cotton for a practical everyday wrap.','A patterned square cloth used in Japan for wrapping gifts and carrying items.','It is a lightweight, reusable alternative to a conventional souvenir bag.','Kyoto craft stores, Hands, LOFT and museum shops.','Common at selected airport shops.','Available from Japanese design stores. ',4.7,635,'https://www.japan.travel/en/local-specialities/local-crafts/'),
 ('Kokeshi wooden doll','小芥子木偶','from ¥1,800',1800,'Home','https://images.unsplash.com/photo-1594736797933-d0f06ba46b9d?auto=format&fit=crop&w=900&q=80','Tohoku craft','Wrap carefully and carry fragile pieces onboard.','A hand-painted, limbless wooden doll from northern Japanese craft tradition.','It is a warm, iconic Japanese handmade keepsake with many regional styles.','Asakusa, Tohoku craft shops and Nakamise Street.','Limited airport availability.','Available from artisan retailers. ',4.7,511,'https://www.japan.travel/en/itineraries/a-downtown-shopping-adventure-in-tokyo/'),
 ('Maneki-neko lucky cat figurine','招财猫摆件','from ¥1,200',1200,'Home','https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=900&q=80','Lucky Japan icon','Choose a small ceramic size for safer packing.','A beckoning-cat figurine traditionally associated with good fortune.','It is an instantly recognisable Japanese symbol and a cheerful home gift.','Asakusa Nakamise, Gotokuji area and museum stores.','Available at selected airports.','Available from Japanese souvenir shops. ',4.6,688,'https://www.japan.travel/en/itineraries/a-downtown-shopping-adventure-in-tokyo/'),
 ('Hario V60 ceramic dripper','Hario V60 陶瓷手冲咖啡滤杯','from ¥1,600',1600,'Home','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80','Japanese coffee design','Carry ceramic versions in hand luggage.','A Japanese-designed pour-over dripper favoured by home coffee brewers.','It is a useful, well-designed souvenir that continues the trip at home.','Kappabashi, Hands, Yodobashi and coffee shops.','Limited airport availability.','Widely available from Hario online. ',4.8,803,'https://www.japan.travel/en/itineraries/a-downtown-shopping-adventure-in-tokyo/'),
 ('Midori MD notebook','MIDORI MD 笔记本','from ¥1,100',1100,'Home','https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=900&q=80','Japanese stationery','Keep it flat in your carry-on.','A minimalist Japanese notebook prized for smooth fountain-pen-friendly paper.','Japan’s stationery culture makes this a useful souvenir for almost anyone.','LOFT, Hands, Itoya and stationery shops.','Available at selected airport shops.','Available from Japanese stationery retailers. ',4.8,721,'https://www.japan.travel/en/guide/shopping-in-japan/'),
 ('Uni Kuru Toga mechanical pencil','三菱自动铅笔','from ¥700',700,'Home','https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80','Stationery essential','Buy multiple colours for small gifts.','A Japanese mechanical pencil with a rotating lead mechanism.','It is compact, affordable and a genuine everyday Japanese-design find.','LOFT, Hands, Don Quijote and stationery shops.','Available at airport stationery stores.','Widely available online. ',4.7,904,'https://www.japan.travel/en/guide/shopping-in-japan/'),
 ('Gachapon capsule toy','扭蛋胶囊玩具','from ¥300',300,'Home','https://images.un','Kawaii surprise','Keep the paper insert with the toy.','A surprise collectible from Japan’s ubiquitous capsule-toy machines.','It is the cheapest and most playful way to bring home Japanese pop culture.','Akihabara, station arcades, malls and Don Quijote.','Selected airport machines.','Some collections available online. ',4.6,1055,'https://www.japan.travel/en/guide/shopping-in-japan/')
) AS v(name,chinese_name,price,price_amount,category,image_url,tag,note,description,why_buy,best_shops,airport,online,rating,review_count,source_url) JOIN countries c ON c.name='Japan';

INSERT INTO product_photos (product_id,image_url,alt_text,position) SELECT p.id,p.image_url,p.name,1 FROM products p WHERE p.country_id=(SELECT id FROM countries WHERE name='Japan');
INSERT INTO product_reviews (product_id,reviewer_name,rating,body,created_at) SELECT p.id,'Aiko N.',p.rating,'A beautifully packaged Japanese pick that was easy to take home and share.',DATE '2026-07-21' FROM products p WHERE p.country_id=(SELECT id FROM countries WHERE name='Japan');
